- link:
    "~/.config/fish/functions/bwc.fish": fish/functions/bwc.fish
    "~/.config/fish/functions/base16-shell-theme.fish": fish/functions/base16-shell-theme.fish
    "~/.config/fish/functions/make-pdf.fish": fish/functions/make-pdf.fish
    "~/.config/fish/config.fish": fish/config.fish
    "~/.config/fish/functions/fisher.fish": fish/fisher/fisher.fish
    "~/.config/fish/fishfile": fish/fishfile

- shell:
    - fisher

